title: Presentation Karaoke
description: >
  Grab 6-200 of your closest friends and present random topics
  to the worst and most random slides ever created.
  Fun, and you just might learn something.
baseurl: "/croedig/presentation_karaoke"

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
